# Generated by Django 3.2.8 on 2022-02-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='repost',
        ),
    ]
